image:
  - macos
  - macos-mojave

environment:
  VAR1: "Value1"

build_script:
  - ps: echo "VAR1 = $env:VAR1"

for:
-
  matrix:
    only:
      - image: macos

  environment:
    VAR1: "Value1"

  build_script:
    - ps: echo "VAR1 for catalina = $env:VAR1"

-
  matrix:
    only:
      - image: macos-mojave
  
  environment:
    VAR1: "Value1"
  
  build_script:
    - ps: echo "VAR1 for mojave = $env:VAR1"

