#image: Windows

environment:
  FIXED_VAR: "Fixed value"


init:
  ps : >-
    echo "BUILD_CLOUD = $env:APPVEYOR_BUILD_WORKER_CLOUD";
    .\\scripts\\hello.ps1

install:
  ps: npm install

build_script:
  ps: echo "Skip this settings"
