image:
  - macos

environment:
  VAR1: true
  FOO:
    secure: Mrgyeo6XYPXgCDJguWpt7Q==
  FOO2: "bar2"

build_script:
  sh: echo "Build"

test_script:
  - sh: echo ${FOO}
  - sh: FOO=BAR node test.js

