image:
  - Visual Studio 2017

environment:
  VAR1: true

init:
  ps : >-
    if ($env:VAR1 -eq $True) {
      Exit-AppVeyorBuild
    }
    git config --global core.autocrlf input

install:
  ps: npm install

build_script:
  ps: echo "Build"
