image:
  - Visual Studio 2017

environment:
  VAR1: true

init:
  ps : >-
    if ($True) {
      echo "Exit"
      Exit-AppVeyorBuild
    } else {
      git config --global core.autocrlf input
    }

install:
  ps: npm install

build_script:
  ps: echo "Build"
