image:
  - macos

environment:
  VAR1: true
  FOO:
    secure: Mrgyeo6XYPXgCDJguWpt7Q==
  FOO2: "bar2"

build_script:
  sh: echo "Build"

test_script:
  - sh: >-
      set -e
      echo "start";
      if [ "${FOO2}" == "bar2" -a "${FOO2}" == "bar2" ]; then
        echo "hello"
      fi

      echo "end"

