build_cloud: local-win10
image: Windows

environment:
  FIXED_VAR: "Fixed value"
  # matrix:
  #   - DEFAULT_VAR1: "Value2"
  #   - DEFAULT_VAR1: "Value1"


init:
  ps : >-
    Exit-AppVeyorBuild;
    echo "DEFAULT_VAR1 = $env:DEFAULT_VAR1";
    echo "VAR1 = $env:VAR1";
    echo (Test-Path env:VAR1);
    if (!(Test-Path env:VAR1)) { echo "Not exist" } else { echo "Exist"}
    if (!(Test-Path env:VAR1)) { $env:VAR1 = $env:DEFAULT_VAR1 }
    echo "merged VAR1 = $env:VAR1";

build_script:
  ps: echo "Skip this settings"

# for:
# -
#   matrix:
#     only:
#       - image: Visual Studio 2017
  
#   install:
#     - ps: if ($env:DEFAULT_VAR1 -eq "Value2") { Exit-AppVeyorBuild }

#   build_script:
#     - ps: echo "VAR1 = $env:VAR1"
#     - ps: echo "VAR1 = $env:VAR1"

# -
#   matrix:
#     only:
#       - image: Visual Studio 2019

#   build_script:
#     - ps: echo "VAR1 = $env:VAR1"

