image:
  - macos
  - macos-mojave

environment:
  DEFAULT_VAR1: "Value1"

init:
  ps : >-
    echo "DEFAULT_VAR1 = $env:DEFAULT_VAR1";
    echo "VAR1 = $env:VAR1";
    if (!(Test-Path Variable:VAR1)) { echo "Not exist" } else { echo "Exist"}
    if ((Test-Path Variable:VAR1) -eq $False) { echo "Not exist" } else { echo "Exist"}
    if ((Test-Path Variable:VAR1) -eq "False") { echo "Not exist" } else { echo "Exist"}

build_script:
  - ps: echo "VAR1 = $env:VAR1"

for:
-
  matrix:
    only:
      - image: macos

#  environment:
#    VAR1: "Value1"

  build_script:
    - ps: echo "VAR1 for catalina = $env:VAR1"

-
  matrix:
    only:
      - image: macos-mojave
  
#  environment:
#    VAR1: "Value1"
  
  build_script:
    - ps: echo "VAR1 for mojave = $env:VAR1"

